# System Config Meta --------------------------------------
job_configs:
    - name: MAX_JOB_NUM
      desc_zh: 每个域最大作业数
    - name: INTERVAL_TIME_OF_ENABLED_REPORT
      desc_zh: 根据cron计算执行间隔时间，如果间隔时间小于此值，则不上报作业运行状态；否则，则上报

executor_configs:
    - name: ALARM_RAISED_ON_EXECUTOR_RESTART
      desc_zh: executor restart是否发送告警
    - name: MAX_SECONDS_FORCE_KILL_EXECUTOR
      desc_zh: executor stop时最长等待时间

console_configs:
    - name: AUTHORIZATION_ENABLED
      desc_zh: 是否使用鉴权

cluster_configs:
    - name: CONSOLE_ZK_CLUSTER_MAPPING
      desc_zh: Console与ZK集群映射关系，用于Console接管其映射ZK集群的Dashboard和域分片。其中Console和ZK集群之间是一对多的关系，一个Console可以接管多个ZK集群，ZK集群之间用逗号隔开。参考配置格式：CONSOLE-GD:/zk1,/zk2;CONSOLE-BJ:/zk3;default:/zk;注意，修改此值后，可能需要等待几分钟才能生效(具体等待时间跟Dashboad刷新时间相关)
    - name: IDC_ZK_CLUSTER_MAPPING
      desc_zh: IDC机房标识与ZK集群映射关系，用于识别某个ZK集群所处的机房。其中IDC机房和ZK集群之间是一对多的关系，一个IDC下面包含多个ZK集群，ZK集群之间用逗号隔开。参考配置格式：gd:/zk1,/zk2;bj:/test,/zk;
    - name: IDC_CONSOLE_ID_MAPPING
      desc_zh: IDC机房标识与Console的映射关系，用于识别某个Console所处的机房。其中IDC机房和Console之间是一对多的关系，一个IDC下面包含多个Console，Console之间用逗号隔开。参考配置格式：gd:CONSOLE-GD;bj:CONSOLE-BJ;
    - name: IDC_CONSOLE_DOMAIN_MAPPING
      desc_zh: IDC机房与Console访问域名的映射关系，用于识别不同机房对应的Console的访问域名。其中IDC机房和域名之间是一对一的关系,一个IDC机房只能对应一个域名。参考配置格式：gd:http://gd-namespace;bj:http://bj-namespace;
